### PR TITLE
Added bugs reported by a-shvedov, added commas to the lists of bugs

### PR DESCRIPTION
**Pull request by nataraj-hates-MS-for-stealing-github**
Added bugs reported by a-shvedov in https://github.com/AFLplusplus/AFLplusplus/issues/286#issuecomment-1506569310, added commas to the lists of bugs

### CODE REVIEW

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
@vanhauser-thc can you please merge this pull request. I have a new bug to add. Better to add it on up to date repo

**Comment by vanhauser-thc** [comment]
@andreafioraldi WDYT?

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
> @nataraj-hates-MS-for-stealing-github I am sorry for the ambiguity that I created in the issue. @andreafioraldi did not find or report the vulnerability. I actually found and reported the vulnerability. I was just mentioning @andreafioraldi because he started a Report the Trophy issue, to bring this CVE to his attention. Again apologies for the confusion.

I am very sorry about it. Will do it right, right now.

**Comment by faran1512** [comment]
> > @nataraj-hates-MS-for-stealing-github I am sorry for the ambiguity that I created in the issue. @andreafioraldi did not find or report the vulnerability. I actually found and reported the vulnerability. I was just mentioning @andreafioraldi because he started a Report the Trophy issue, to bring this CVE to his attention. Again apologies for the confusion.
> 
> I am very sorry about it. Will do it right, right now.

Thanks. No problem

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
ping

**Comment by vanhauser-thc** [comment]
I can merge it but @andreafioraldi is the one generating the web pages …

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
> I can merge it but @andreafioraldi is the one generating the web pages …

He will do it sooner or later, I hope, and when it is merged, it will go there automatically.

Thanks!

**Pull request merged**
